import {
    f_display_test_selection_or_run_selected_test_and_print_summary,
    f_o_test
} from "https://deno.land/x/deno_test_server_and_client_side@1.1/mod.js"

import {
    f_add_css,
    f_s_css_prefixed,
    o_variables, 
    f_s_css_from_o_variables
} from "https://deno.land/x/f_add_css@1.1/mod.js"

o_variables.n_rem_font_size_base = 1. // adjust font size, other variables can also be adapted before adding the css to the dom
o_variables.n_rem_padding_interactive_elements = 0.5; // adjust padding for interactive elements 
f_add_css(
    `
    body{
        min-height: 100vh;
        min-width: 100vw;
        /* background: rgba(0,0,0,0.84);*/
        display:flex;
        justify-content:center;
    }
    canvas{
        width: 100%;
        height: 100%;
        position:fixed;
        z-index:-1;
    }
    .app{
        max-width: 1000px;
        width:100%;
        height: 100vh;
        display:flex;
        flex-direction: column;
        justify-content:flex-end;
    }
    .a_o_msg{
        overflow:scroll;
    }
    ${
        f_s_css_from_o_variables(
            o_variables
        )
    }
    `

);

// } from "https://deno.land/x/f_add_css@[version]/mod.js"

//readme.md:start
//md: ![./logo_wide.png](./logo_wide.png)
//readme.md:end

//./readme.md:start
//md: # changelog
//md: 
//./readme.md:end


import {
    f_o_html__and_make_renderable,
}
from 'https://deno.land/x/f_o_html_from_o_js@2.7/mod.js'


import {
    f_n_idx_binding_from_params,
    f_o_gpu_gateway, 
    f_o_gpu_gateway__from_simple_fragment_shader,
    f_o_gpu_gateway_webgpu,
    f_o_gpu_gateway_webgpu_dataitem__buffer_from_v_as_type,
    f_o_gpu_texture__from_o_web_api_object,
    f_render_o_gpu_gateway,
    f_render_o_gpu_gateway_webgpu,
    f_s_autogenerated_accessor_functions,
    f_s_binding_declaration__from_o_gpu_gateway_webgpu,
    f_update_data_in_o_gpu_gateway,
    f_update_data_in_o_gpu_gateway_webgpu,
}
from 'https://deno.land/x/gpugateway@0.3/mod.js'

let o_canvas = document.createElement('canvas');
o_canvas.width = window.innerWidth
o_canvas.height = window.innerHeight
document.body.appendChild(o_canvas);

let o_gpu_gateway = f_o_gpu_gateway(
    o_canvas, 
    `#version 300 es
    in vec4 a_o_vec_position_vertex;
    out vec2 o_trn_nor_pixel;
    void main() {
        gl_Position = a_o_vec_position_vertex;
        o_trn_nor_pixel = (a_o_vec_position_vertex.xy) / 2.0; // Convert from clip space to texture coordinates
    }`,
    `#version 300 es
    precision mediump float;
    // incoming variables
    in vec2 o_trn_nor_pixel;
    // outgoing variables
    out vec4 fragColor;
    // data passed from javascript 
    uniform float n_ms_time;
    uniform vec2 o_trn_nor_mouse;
    uniform vec2 o_scl_canvas;
    void main() {
        float nt = n_ms_time *.0001;
        vec2 o_trn_nor_p = o_trn_nor_pixel * vec2(1., o_scl_canvas.y/o_scl_canvas.x);
        vec2 o_trn_nor_m = (o_trn_nor_mouse -.5) * vec2(1., o_scl_canvas.y/o_scl_canvas.x);
        float n_len_diff_mp = length(o_trn_nor_p-o_trn_nor_m);
        float nc = length(o_trn_nor_p);
        float ns = max(abs(o_trn_nor_p.x), abs(o_trn_nor_p.y));
        //nc = sin(nc*33.+nt);
        //ns = sin(ns*33.-nt);
        float ni = nc;
        ni = .5;
        float n = ni * ns + (1.-ni)*nc;
        // n = nc+ns;
        float no = .2;
        float nr = sin(nc*33.+nt)*.5 + sin(ns*33.-nt)*.5;
        nr = pow(nr, 2.);
        float ng = sin(nc*33.+nt+no)*.5 + sin(ns*33.-nt-no)*.5;
        ng = pow(ng, 2.+3.*o_trn_nor_mouse.x);
        float nb = sin(nc*33.+nt+no)*.5 + sin(ns*33.-nt-no)*.5;
        nb = pow(nb, 1.+3.*o_trn_nor_mouse.y);
        fragColor = vec4(
            vec3( 
               nr, ng, nb
            ),
            1.
        );
        n_len_diff_mp = pow(n_len_diff_mp,1./5.);
        fragColor *= vec4(vec3(1.-n_len_diff_mp),1.);
    }
    `,
)

let f_resize = ()=>{
    o_canvas.width = window.innerWidth
    o_canvas.height = window.innerHeight
    f_update_data_in_o_gpu_gateway(
        {o_scl_canvas: [
            o_canvas.width,
            o_canvas.height
        ]}, 
        o_gpu_gateway, 
    )
}
window.addEventListener('resize',()=>{
    f_resize()
});
f_resize()

let n_id_raf = 0;
let f_raf = function(){
    n_id_raf = window.requestAnimationFrame(f_raf);
    f_update_data_in_o_gpu_gateway(
        {
            n_ms_time: window.performance.now()
        }, 
        o_gpu_gateway, 
    )
    f_render_o_gpu_gateway(
        o_gpu_gateway, 
    );
}
n_id_raf = window.requestAnimationFrame(f_raf);



// Determine the current domain
const s_hostname = window.location.hostname;

// Create the WebSocket URL, assuming ws for http and wss for https
const s_protocol_ws = window.location.protocol === 'https:' ? 'wss:' : 'ws:';
const s_url_ws = `${s_protocol_ws}//${s_hostname}:${window.location.port}`;

// Create a new WebSocket instance
const o_ws = new WebSocket(s_url_ws);

// Set up event listeners for your WebSocket
o_ws.onopen = function(o_e) {
    console.log('WebSocket is open now.');
};

o_ws.onerror = function(o_e) {
    console.error('WebSocket error observed:', o_e);
};

o_ws.onmessage = function(o_e) {

    let o = JSON.parse(o_e.data);
    console.log(o.s_js)
    let f = new Function('o_state',o.s_js);
    console.log(f)
    f(o_state);
    // console.log( typeof o_e.data);
};
// To send a message to the server
// o_ws.send('Your message here');

// To close the WebSocket
// o_ws.close();

let o_state = {
    s_msg: '', 
    a_o_msg: [], 
    o_trn_nor_mouse: [0.2,0.2]
}
window.o_state = o_state
window.addEventListener('pointermove', (o_e)=>{
    o_state.o_trn_nor_mouse = [
        (o_e.clientX / window.innerWidth), 
        1.-(o_e.clientY / window.innerHeight), 
    ];
    f_update_data_in_o_gpu_gateway(
        {o_trn_nor_mouse: o_state.o_trn_nor_mouse}, 
        o_gpu_gateway, 
    )
})
let f_send_msg = function(){
    console.log(o_state)
    if(o_state?.s_msg?.trim() != ''){
        o_ws.send(
            JSON.stringify(
                {
                    s_msg: o_state.s_msg
                }
            )
        )
        o_state.s_msg = '';
        o_state?.o_js__msg_input?._f_update();
    }
}
window.addEventListener('keydown', (o_e)=>{
    if(o_e.key == 'Enter'){
        f_send_msg()
    }
})
// //readme.md:start
document.body.appendChild(
    await f_o_html__and_make_renderable(
        {
            s_tag: 'div', 
            class: "app",
            a_o: [
                Object.assign(
                    o_state, 
                    {
                        o_js__a_o_msg: {
                            f_o_jsh: ()=>{
                                return {
                                    class: "a_o_msg",
                                    a_o: [
                                        o_state.a_o_msg.map(o=>{
                                            return {
                                                style: [
                                                    'display:flex',
                                                    'flex-direction:row',
                                                    `justify-content: ${(o.s_uuidv4 == o_state.s_uuidv4) ? 'end' : 'start'}`,
                                                    'align-items:end'
                                                ].join(';'),
                                                a_o: [
                                                    {
                                                        innerText: o.s_msg
                                                    },
                                                    {
                                                        style: 'color: darkgray;padding-left: 1rem; font-size:10px',
                                                        innerText: new Date(o.n_ts_ms).toISOString()
                                                    }
                                                ]
                                            }
                                        })
                                    ]
                                }
                            }
                        }
                    }
                ).o_js__a_o_msg,
                Object.assign(
                    o_state, 
                    {
                        o_js__msg_input: {
                            f_o_jsh: ()=>{
                                return {
                                    s_tag: 'textarea', 
                                    value: o_state.s_msg,
                                    oninput: (o_e)=>{
                                        o_state.s_msg = o_e.target.value;
                                    }, 
                                    //if no 's_tag' is set, the element will be a 'div' element
                                    innerText: "i am a DIV!"
                                }
                            }
                        }
                    }
                ).o_js__msg_input,
                {
                    s_tag: 'button', 
                    innerText: "Send !", 
                    onclick: ()=>{
                        f_send_msg()
                    }
                }, 
            ]
        }
    )
);
// //readme.md:end